### ISSUE TITLE
10.1093/ptep/ptad061 not in the repo

### ISSUE THREAD

**Issue by agentilb** [cern-sis/issues-scoap3#165]
Article which was sent by OUP on 08/06, but doesn't seem to be in the repository: 

<img width="625" alt="Screenshot 2023-06-13 at 16 22 21" src="https://github.com/cern-sis/issues-scoap3/assets/12181904/8db1f17a-7c8b-477d-81ae-2d6853d22760">

Could you please check why?

**Comment by ErnestaP** [comment]
Hi @agentilb , looks like these folders were completely empty. 
I checked it on our side, I see that the size of the files is 0 (5th column):
<img width="592" alt="Screenshot 2023-06-15 at 14 28 54" src="https://github.com/cern-sis/issues-scoap3/assets/36658177/6f1cd89c-735f-4fea-9d42-61ce5c31a9e7">


As well, I see that the size was already 0 when they uploaded the files. It is visible in your provided screenshot, 2nd column. Can you please ask OUP to upload full files to the FTP, so that we could harvest them?

**Comment by agentilb** [comment]
Email sent to the publisher

**Comment by ErnestaP** [comment]
Hi @agentilb, the article is in repo: https://repo.scoap3.org/records/78326
